@startuml
enum DataTypeIEC61360 <<enumeration>> {
  DATE
  STRING
  STRING_TRANSLATABLE
  INTEGER_MEASURE
  INTEGER_COUNT
  INTEGER_CURRENCY
  REAL_MEASURE
  REAL_COUNT
  REAL_CURRENCY
  BOOLEAN
  IRI
  IRDI
  RATIONAL
  RATIONAL_MEASURE
  TIME
  TIMESTAMP
  HTML
  BLOB
  FILE
}
@enduml