////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

Illustrations:
Plattform Industrie 4.0; Anna Salari, Publik. Agentur für Kommunikation GmbH, designed by Publik. Agentur für Kommunikation GmbH
////

[[part3a-terms-and-definitions]]
= Terms, Definitions and Abbreviations

[glossary]
== Terms and Definitions

+++Please note+++:

the definitions of terms are only valid in a certain context. This glossary applies only within the context of this document. For a more extensive list, please refer to Part 1 of the document series.

If available, definitions were taken from IEC 63278-1 DRAFT, July 2022, and from IEC 61360.

application

software functional element specific to the solution of a problem in industrial-process measurement and control


====
Note 1 to entry: an application can be distributed among resources and may communicate with other applications.
====


* [SOURCE: IEC TR 62390:2005-01, 3.1.2]

attribute

data element of a _property_, a relation, or a class in information technology

* [SOURCE: ISO/IEC Guide 77-2, ISO/IEC 27460, IEC 61360]

Asset Administration Shell (AAS)

standardized digital representation of an asset


====
Note 1 to entry: Asset Administration Shell and Administration Shell are used synonymously.
====


* [SOURCE: IEC 63278-1, note added]

class

description of a set of objects that share the same _attributes_, _operations_, methods, relationships, and semantics

* [SOURCE: IEC TR 62390:2005-01, 3.1.4]

concept

unit of knowledge created by a unique combination of characteristics

* [SOURCE: EC 63278-1; IEC 61360-1:2016, 3.1.8; ISO 22274:2013, 3.7]

enumeration

list of named constants called enumerators, each numerator name in the enumeration being unambiguous

* [SOURCE:IEC 61360-1_2017]

identifier (ID)

identity information that unambiguously distinguishes one entity from another one in a given domain


====
Note 1 to entry: there are specific identifiers, e.g. UUID Universal unique identifier, IEC 15418 (GS1).
====


* [SOURCE: Glossary Industrie 4.0]

minimum value

lower bound of a range of values in which the said value is meaningful


====
EXAMPLE 1: lowest value specified of a quantity, established for a specified set of operating conditions at which a
====


component, device, equipment, or system can operate and perform according to specified requirements.


====
Note 1 to entry: additional information about the nature of the value can be obtained from the definition of the
====


_Property_ information object to which the value belongs.

* [SOURCE:IEC 61360-1_2017]

maximum value

upper bound of a range of values in which the said value is meaningful


====
EXAMPLE 1: highest value specified of a quantity, established for a specified set of operating conditions at which a component, device, equipment, or system can operate and perform according to specified requirements.
====



====
Note 1 to entry: additional information about the nature of the value can be obtained from the definition of the
====


_Property_ information object to which the value belongs.

* [SOURCE:IEC 61360-1_2017]

nominal value

value of a quantity used to designate or identify an item with its value, and not necessarily corresponding to the real value of the property


====
Note 1 to entry: additional information about the nature of the value can be obtained from the definition of the
====


_Property_ information object to which the value belongs.

* [SOURCE:IEC 61360-1_2017]

non-quantitative property

property that identifies or describes an object by means of codes, abbreviations, names, references or descriptions


====
EXAMPLE 1: typical information content of non-quantitative properties is items such as codes, abbreviations,
====


names, references, or descriptions.

* [SOURCE: IEC 61360-2:201 7– based on IEC 61360-2:2012, 3.28, modified – "data element type" is replaced by "property" in the term and definition.]

property

defined characteristic suitable for the description and differentiation of products or components


====
Note 1 to entry: the concept of type and instance applies to properties.
====



====
Note 2 to entry: this definition applies to properties as described in IEC 61360/ ISO 13584-42.
====



====
Note 3 to entry: the property types are defined in dictionaries (like IEC component data dictionary or ECLASS), they do not have a value. The property type is also called data element type in some standards.
====



====
Note 4 to entry: the property instances have a value and are provided by the manufacturers. A property instance is also called property-value pair in certain standards.
====



====
Note 5 to entry: properties include nominal value, actual value, runtime variables, measurement values, etc.
====



====
Note 6 to entry: a property describes one characteristic of a given object.
====



====
Note 7 to entry: a property can have attributes such as code, version, and revision.
====



====
Note 8 to entry: the specification of a property can include predefined choices of values.
====


* [SOURCE: according to ISO/IEC Guide 77-2] as well as [SOURCE: according Glossary Industrie 4.0]

qualifier

well-defined element associated with a _property_ instance or _submodel element_, restricting the value statement to a certain period of time or use case


====
Note 1 to entry: qualifier can have associated values.
====


* [SOURCE: according to IEC 62569-1]

quantitative property

property with a numerical value representing a physical quantity, a quantity of information or a count of objects

* [SOURCE: IEC 61360-1_2017 – based on IEC 61360-2:2012, 3.40, modified – "data element type" is replaced by "property"]

Submodel

container of SubmodelElements defining a hierarchical structure consisting of SubmodelElements

* [SOURCE: IEC 63278-1]

SubmodelElement

elements in a Submodel

* [SOURCE: IEC 63278-1]



==  Abbreviations Used in Document

[width="100%",cols="21%,79%",options="header",]
|===
|*Abbreviation* |*Description*
|AAS |Asset Administration Shell
|AASX |Package file format for the Asset Administration Shell
|AML |AutomationML
|API |Application Programming Interface
|BITKOM |Bundesverband Informationswirtschaft, Telekommunikation und neue Medien e. V.
|BLOB |Binary Large Object
|CDD |Common Data Dictionary
|GUID |Globally unique identifier
|I4.0 |Industrie 4.0
|ID |Identifier
|IDTA |Industrial Digital Twin Association
|IEC |International Electrotechnical Commission
|IRDI |International Registration Data Identifier
|IRI |Internationalized Resource Identifier
|ISO |International Organization for Standardization
|JSON |JavaScript Object Notation
|MIME |Multipurpose Internet Mail Extensions
|OPC |Open Packaging Conventions (ECMA-376, ISO/IEC 29500-2)
|OPCF |OPC Foundation
|OPC UA |OPC Unified Architecture
|PDF |Portable Document Format
|RAMI4.0 |Reference Architecture Model Industrie 4.0
|RDF |Resource Description Framework
|REST |Representational State Transfer
|RFC |Request for Comment
|SOA |Service Oriented Architecture
|UML |Unified Modelling Language
|URI |Uniform Resource Identifier
|URL |Uniform Resource Locator
|URN |Uniform Resource Name
|UTC |Universal Time Coordinated
|VDE |Verband der Elektrotechnik, Elektronik und Informationstechnik e.V.
|VDI |Verein Deutscher Ingenieure e.V.
|VDMA |Verband Deutscher Maschinen- und Anlagenbau e.V.
|W3C |World Wide Web Consortium
|XML |eXtensible Markup Language
|ZIP |archive file format that supports lossless data compression
|ZVEI |Zentralverband Elektrotechnik- und Elektronikindustrie e. V.
|===

