////
Copyright (c) 2023 Industrial Digital Twin Association

This work is licensed under a [Creative Commons Attribution 4.0 International License](
https://creativecommons.org/licenses/by/4.0/). 

SPDX-License-Identifier: CC-BY-4.0

////

= Summary and Outlook

This document provides a metamodel for specifying a data specification template for defining concept descriptions for properties and values.
This data specification templates are conformant to IEC 61360.

This document is part of the document series "Specification of the Asset Administration Shell".

Additional parts of the document series cover (see xref:bibliography.adoc#bib14[[14\]]):

* the information model that is the basis for file exchange and interface payload definition (IDTA-01001, Part 1),
* interfaces and APIs for accessing the information of Asset Administration Shells (IDTA-01002, Part 2),
* security aspects including access control (IDTA-01004, part 4),
* a file exchange format AASX (IDTA-01005, Part 5),

Additional parts are in preparation:

* physical units as used to define the semantics of quantifiable properties in IEC 61360 (IDTA-01003-b, Part 3b).