@startuml
!$classes = "https://raw.githubusercontent.com/admin-shell-io/aas-specs-iec61360/IDTA-01003-a-3-1_working/documentation/IDTA-01003-a/modules/ROOT/partials/diagrams/classes"

!include $classes/key.puml
!include $classes/reference.puml
!include $classes/enum-reference-types.puml
!include $classes/enum-key-types.puml

Reference .> ReferenceTypes
Reference ..> Key
Key .> KeyTypes
@enduml