@startuml
!$classes = "https://raw.githubusercontent.com/admin-shell-io/aas-specs-iec61360/IDTA-01003-a-3-1_working/documentation/IDTA-01003-a/modules/ROOT/partials/diagrams/classes"

skinparam packageStyle rectangle

package "Data Specification Templates - Part 1"  {
    !include $classes/data-specification-template.puml
    !include $classes/data-specification-content.puml
}

!include $classes/data-specification-iec61360.puml

package "Concept Descriptions - Part 1"  {
    !include $classes/concept-description.puml
}

DataSpecificationContent <|- DataSpecificationIec61360
ConceptDescription <.. DataSpecificationIec61360: may be used as\nData Specification
DataSpecification ..> DataSpecificationContent
@enduml